web-php:
#  image: php:5.6-apache
# Requires php:5.6-apache image.
  build: ../images/ext/php5.6-apache
  ports:
# Own IP or from hosts.
    - "127.0.10.2:8080:80"
  volumes:
    - ./www:/var/www/html
  links:
    - db

db:
  build: ../images/base/mysql-ee6ac037ab647e0de9dbeb4e064610a95cb6df4a/5.7
  volumes:
    - ./mysql-conf.d:/etc/mysql/conf.d/
#    - /my/own/datadir:/var/lib/mysql
  ports:
    - "3366:3306"
#  expose: # Without publishing to the host machine - only be accessible to linked services.
#    - "3306"
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: testdb
#    MYSQL_USER: test
#    MYSQL_PASSWORD: test

phpmyadmin:
  build: ../images/base/phpmyadmin-master
  ports:
    - "8090:8080"
  links:
    - db
