version: '3'
services:
  nginx:
    build: ./images/nginx
    container_name: lnmp-nginx
    ports:
      - 8080:80
    volumes:
#      - ./images/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./images/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./www:/var/www/html
    depends_on:
      - db
      - php
    networks:
      base_net:
        ipv4_address: 172.16.238.4

  php:
    build: ./images/php7.1-fpm
    container_name: lnmp-php
    ports:
      - 9000
    user: ${UID}:${UID}
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      base_net:
        ipv4_address: 172.16.238.11

  db:
    image: mysql:5.7
    container_name: lnmp-db
    volumes:
      - ./images/mysql/local.cnf:/etc/mysql/conf.d/local.cnf
    ports:
      - 3366:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    networks:
      base_net:
        ipv4_address: 172.16.238.10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: lnmp-phpmyadmin
    ports:
      - 8090:80
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: 172.16.238.10
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      base_net:

networks:
  base_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
