version: '3'
services:
  elasticsearch:
    build: ../elasticsearch1.5
    container_name: base-elasticsearch
    ports:
      - "127.0.10.1:9301:9200"
    command: elasticsearch -Des.discovery.zen.ping.multicast.enabled=false -Des.cluster.name="elasticsearchtest" -Des.node.local=true -Des.index.store.type="memory" -Des.store.fs.memory.enabled=true -Des.gateway.type="none" -Des.gateway.type="none"
  #    Plugins might be installed manually or inherited from the base image:
  #    /usr/share/elasticsearch/bin/plugin -install mobz/elasticsearch-head # http://localhost:9300/_plugin/head/
  #    /usr/share/elasticsearch/bin/plugin -install royrusso/elasticsearch-HQ # http://localhost:9300/_plugin/HQ/
